### ISSUE TITLE
Disconnected from the server

### ISSUE THREAD

**Issue by ThaiseEmilio** [stevenpbachman/rapidLC_top#104]
Dear Steven, 
I have tried to run a batch assessment but when I try to upload the .csv file I got an error message saying that I am disconnected from the server. I have tried different computers, browsers and files. All return the same error. Could that be a bug or is more likely to be something I am doing wrong? Please see attached the .csv file I have been using. 
Many thanks!
Thaise

[amz-palms-plots.csv](https://github.com/stevenpbachman/rapidLC_top/files/9384062/amz-palms-plots.csv)

**Comment by stevenpbachman** [comment]
Hi Thaise, hope all well with you! Sorry you were having issues with the tool - it is quite delicate ;) I'm not sure what the problem was, but I tried a couple of things: 1) split into smaller batches ~50 seems ok. 2) I just created a new csv file and cuta and paste in your names. Restart the app by reloading the page - it can take a minute or two. I just ran the first 50 and it worked ok. Results should be attached. I will try the next batch now.
[results.csv](https://github.com/stevenpbachman/rapidLC_top/files/9384726/results.csv)

**Comment by stevenpbachman** [comment]
oh wait, I think I spotted it. Should be `name_in`, not `names_in` - that is probably it.

**Comment by ThaiseEmilio** [comment]
Thanks Steven! It was exactly that, well spotted! I just tried again with
the corrected spreadsheet and it is working just fine.
 All is well here :) I hope that with you too.
Cheers,
Thaise

--
Dr. Thaise Emilio (website <https://thaise-emilio.weebly.com/>)
Department of Plant Biology, Institute of Biology
University of Campinas - UNICAMP
<http://www.internationaloffice.unicamp.br/hotsite/>
CEP 13083‐970, Campinas, SP, Brazil
Phone +55 19 3521-6172
Neotropical Network of Palm Specialists - Let's collaborate!
<https://neotroppalms.weebly.com/> 🌴
